name: Neovim Config Auto-Merge

on:
  push:
    branches:
      - jconf

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm git base-devel neovim unzip curl lua

      - name: Set up Git safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: jconf

      - name: Check Lua syntax
        run: |
          find . -name '*.lua' -print0 | xargs -0 -n1 luac -p

      - name: Run Neovim headless to catch runtime errors
        run: |
          nvim --headless "+quit"

      - name: Configure git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge jconf into master
        run: |
          gh pr create \
            --title "Auto update jconf" \
            --body "Automated PR from workflow" \
            --base master \
            --head jconf || echo "PR already exists or failed"\
            && gh pr create \
            --title "Auto update jconf" \
            --body "Automated PR from workflow" \
            --base betterConfig \
            --head jconf || echo "PR already exists or failed"

      - name: Enable Auto-Merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_INFO=$(gh pr list --head jconf --state open --limit 2 --json number -q '.[0].number')
          if [ -n "$PR_INFO" ]; then
            echo "Found PR #$PR_INFO for 'jconf' branch. Attempting auto-merge..."
            if gh pr merge "$PR_INFO" --auto --merge; then
              echo "Auto-merge enabled successfully."
            else
              echo "Auto-merge failed."
            fi
          else
            echo "No open PR found for 'jconf' branch."
          fi

