name: Auto PR

on:
  push:
    branches:
      - jconf

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Auto update jconf" \
            --body "Automated PR from workflow" \
            --head jconf \
            --base main
