name: Test and Create PR from jconf to master

on:
  push:
    branches:
      - jconf

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm git base-devel neovim unzip curl lua

      - name: Set up Git safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout jconf branch
        uses: actions/checkout@v3
        with:
          ref: jconf

      - name: Check Lua syntax
        run: |
          find . -name '*.lua' -print0 | xargs -0 -n1 luac -p

      - name: Run Neovim headless to catch runtime errors
        run: nvim --headless "+quit"

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR: sync jconf branch"
          title: "Auto PR: Merge jconf into master"
          body: "Automatically created by GitHub Actions."
          base: master
          branch: "auto-pr-jconf-to-master"   # branch the action creates/updates with changes
          draft: false
          delete-branch: false
