name: Test and Create PR from jconf to master

on:
  push:
    branches:
      - jconf

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for existing PR
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EXISTING_PR=$(gh pr list --head jconf --base main --state open --json number --jq '.[0].number' || echo "")
          echo "existing_pr=$EXISTING_PR" >> $GITHUB_OUTPUT

      - name: Create PR if none exists
        if: steps.check_pr.outputs.existing_pr == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr create --title "Auto update jconf" --body "Automated PR from workflow" --head jconf --base main --json number --jq '.number')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Set PR number for auto-merge
        run: |
          echo "pr_number=${{ steps.check_pr.outputs.existing_pr != '' && steps.check_pr.outputs.existing_pr || steps.create_pr.outputs.pr_number }}" >> $GITHUB_OUTPUT

      - name: Enable Auto-Merge on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.check_pr.outputs.existing_pr != '' && steps.check_pr.outputs.existing_pr || steps.create_pr.outputs.pr_number }}
          REPO: ${{ github.repository }}
        run: |
          curl -X PUT \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/auto-merge \
            -d '{"enabled":true,"merge_method":"merge"}'
