name: Auto PR

on:
  push:
    branches:
      - jconf

jobs:
  create-pr:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm git base-devel curl tar

          # Install GitHub CLI
          GH_VERSION=$(curl -s https://api.github.com/repos/cli/cli/releases/latest | grep '"tag_name":' | cut -d '"' -f 4)
          curl -L -o gh.tar.gz "https://github.com/cli/cli/releases/download/${GH_VERSION}/gh_${GH_VERSION#v}_linux_amd64.tar.gz"
          tar -xzf gh.tar.gz
          cp gh_*/bin/gh /usr/local/bin/
          chmod +x /usr/local/bin/gh
          gh --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Auto update jconf" \
            --body "Automated PR from workflow" \
            --head jconf \
            --base main
