name: Auto PR

on:
  push:
    branches:
      - jconf

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git branches
        run: |
          git fetch origin main
          git fetch origin jconf
          git checkout jconf

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Auto update jconf" \
            --body "Automated PR from workflow" \
            --head jconf \
            --base main
