name: Rebase

on:
  push:
    branches: [master]

jobs:
  rebase-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: master  # branch you want to rebase

      - name: Setup git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin
        
      - name: Rebase branch onto main
        run: |
          git rebase origin/betterConfig --force
          

      - name: Force push rebased branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:your-branch-name --force
