name: Rebase Branch on Master Push

on:
  push:
    branches:
      - master

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Rebase feature branch onto master with auto-resolve
        run: |
          git fetch origin
          git checkout josh_config
          git rebase origin/master --strategy-option=theirs || (git rebase --abort && git reset --hard origin/josh_config)
          git push origin josh_config --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
